### ISSUE TITLE
Não há nenhum trabalho de SO?

### ISSUE THREAD

**Issue by sirNugg3ts** [ISEC-estudantes/Lista-de-Repos#9]
:(

**Comment by OnikenX** [comment]
Eu tenho um trabalho aqui no repo mas ele não funciona corretamente, tal como o meu trabalho de P, ele esta perfeito para a meta 1 de quando foi feito mas a meta 2 foi um completo desastre, thou passei, achas de que devo adicionar à lista? https://github.com/ISEC-estudantes/MSGDIST

**Comment by OnikenX** [comment]
Já existia um mas agora já meti o meu.
